import { createHmac,scrypt as scryptCallback,timingSafeEqual } from 'node:crypto';
import { promisify } from 'node:util';
import { readCookie } from './http';
const scrypt=promisify(scryptCallback);const COOKIE_NAME='cd_admin_session';const SESSION_SECONDS=60*60*8;
function required(name:'ADMIN_EMAIL'|'ADMIN_PASSWORD_HASH'|'ADMIN_SESSION_SECRET'){const value=process.env[name];if(!value)throw new Error(`Missing required environment variable: ${name}`);if(name==='ADMIN_SESSION_SECRET'&&Buffer.byteLength(value,'utf8')<32)throw new Error('ADMIN_SESSION_SECRET must contain at least 32 bytes');return value}
function signature(payload:string){return createHmac('sha256',required('ADMIN_SESSION_SECRET')).update(payload).digest('base64url')}
export async function verifyPassword(password:string){const [algorithm,salt,expectedHex]=required('ADMIN_PASSWORD_HASH').split('$');if(algorithm!=='scrypt'||!salt||!expectedHex||!/^[a-f0-9]{128}$/i.test(expectedHex))return false;const actual=(await scrypt(password,salt,64)) as Buffer;const expected=Buffer.from(expectedHex,'hex');return timingSafeEqual(expected,actual)}
export function createSessionCookie(email:string){const payload=Buffer.from(JSON.stringify({email,exp:Math.floor(Date.now()/1000)+SESSION_SECONDS})).toString('base64url');const secure=process.env.NETLIFY_DEV==='true'?'':' Secure;';return `${COOKIE_NAME}=${encodeURIComponent(`${payload}.${signature(payload)}`)}; Path=/; HttpOnly;${secure} SameSite=Strict; Max-Age=${SESSION_SECONDS}`}
export function clearSessionCookie(){return `${COOKIE_NAME}=; Path=/; HttpOnly; Secure; SameSite=Strict; Max-Age=0`}
export function requireAdmin(request:Request){const token=readCookie(request,COOKIE_NAME);if(!token)return null;const [payload,providedSignature]=token.split('.');if(!payload||!providedSignature)return null;const expected=Buffer.from(signature(payload));const provided=Buffer.from(providedSignature);if(expected.length!==provided.length||!timingSafeEqual(expected,provided))return null;try{const session=JSON.parse(Buffer.from(payload,'base64url').toString('utf8')) as {email:string;exp:number};if(session.exp<=Math.floor(Date.now()/1000)||session.email.toLowerCase()!==required('ADMIN_EMAIL').toLowerCase())return null;return session}catch{return null}}
